package sigs

const upstreamListTemplate = `
package generated

// THIS IS AN AUTOGENERATED FILE, DO NOT EDIT BY HAND
// this package supports exported functions on SIGs and their associated
// subprojects and is generated by parsing SIG information at
//
// https://raw.githubusercontent.com/kubernetes/community/master/sigs.yaml
//
// this file SHOULD NOT export any methods as its intention is simply to
// provide data for eventually exported functions

// SIGSet is the set of SIGs generated by KEP tooling helpers
// DO NOT EDIT BY HAND
var SIGSet = map[string]bool{
        {{ with .SIGs }}
                {{ range . }}
                        "{{canonicalSIGName .Name }}": true,
                {{ end }}
        {{ end }}
}

// SIGSubprojectMapping groups subprojects by their owning SIG
// DO NOT EDIT BY HAND
var SIGSubprojectMapping = map[string]map[string]bool{
         {{ with .SIGs }}
                {{ range . }}
                        "{{ canonicalSIGName .Name }}": map[string]bool {
                                {{ with .Subprojects }}
                                        {{ range . }}
                                                "{{ canonicalName .Name }}": true,
                                        {{ end }}
                                {{ end }}
                        },
                {{ end }}
        {{ end }}

}

var SIGList = []string{
        {{ with .SIGs }}
                {{ range . }}
                        "{{ canonicalSIGName .Name }}",
                {{ end }}
        {{ end }}
}
`
