// Code generated by counterfeiter. DO NOT EDIT.
package eventsfakes

import (
	sync "sync"

	events "github.com/calebamiles/keps/pkg/keps/events"
)

type FakeFetcher struct {
	GetStub        func(events.Lifecycle) (events.Occurrence, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 events.Lifecycle
	}
	getReturns struct {
		result1 events.Occurrence
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 events.Occurrence
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFetcher) Get(arg1 events.Lifecycle) (events.Occurrence, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 events.Lifecycle
	}{arg1})
	fake.recordInvocation("Get", []interface{}{arg1})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFetcher) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeFetcher) GetCalls(stub func(events.Lifecycle) (events.Occurrence, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeFetcher) GetArgsForCall(i int) events.Lifecycle {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFetcher) GetReturns(result1 events.Occurrence, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 events.Occurrence
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) GetReturnsOnCall(i int, result1 events.Occurrence, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 events.Occurrence
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 events.Occurrence
		result2 error
	}{result1, result2}
}

func (fake *FakeFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ events.Fetcher = new(FakeFetcher)
