// This file was generated by github.com/nelsam/hel.  Do not
// edit this code by hand unless you *really* know what you're
// doing.  Expect any changes made manually to be overwritten
// the next time hel regenerates this file.

package porcelain_test

type mockTokenProvider struct {
	ValueCalled chan bool
	ValueOutput struct {
		Ret0 chan string
		Ret1 chan error
	}
}

func newMockTokenProvider() *mockTokenProvider {
	m := &mockTokenProvider{}
	m.ValueCalled = make(chan bool, 100)
	m.ValueOutput.Ret0 = make(chan string, 100)
	m.ValueOutput.Ret1 = make(chan error, 100)
	return m
}
func (m *mockTokenProvider) Value() (string, error) {
	m.ValueCalled <- true
	return <-m.ValueOutput.Ret0, <-m.ValueOutput.Ret1
}
